{% set data = load_setup_py_data() %}

package:
  name: h2o
  version: {{ data.get("version") }}

source:
  path: ../..

requirements:
  build:
    - python >=2.7,<3|>=3.5
    - pip >=9.0.1
    - setuptools
    - colorama >=0.3.7
    - future >=0.15.2
    - tabulate >=0.7.5
    - requests >=2.10

  run:
    - python >=2.7,<3|>=3.5
    - colorama >=0.3.7
    - future >=0.15.2
    - tabulate >=0.7.5
    - requests >=2.10

about:
  home: https://github.com/h2oai/h2o-3.git
  license: Apache License Version 2.0
  license_family: Apache
